version: '3'

services:
  web:
    container_name: wog
    build: .
    ports:
      - "4443:5000"
    networks:
      - my_app


  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    ports:
      - "4444:4444"
      - "4443:4443"
    networks:
      - my_app

  chrom:
    container_name: selenium-chrome-node
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4443
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4444
    networks:
      - my_app

networks:
  my_app:
    driver: bridge


